services:
  api:
    build: ./fastapi_app
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "8000:8000"

  streamlit:
    build: ./streamlit_app
    env_file: .env
    environment:
      API_HOST: api
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    depends_on:
      - api
