apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: datalake
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 31235
    - name: native
      port: 9000
      targetPort: 9000
  type: NodePort
