# ------------------
# HDFS: NameNode
# ------------------
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: datalake
spec:
  selector:
    app: hdfs-namenode
  ports:
    - port: 9870
      targetPort: 9870
      name: web
    - port: 9000
      targetPort: 9000
      name: rpc
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  namespace: datalake
spec:
  selector:
    matchLabels:
      app: hdfs-namenode
  serviceName: "hdfs-namenode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          env:
            - name: CLUSTER_NAME
              value: testcluster
          ports:
            - containerPort: 9870
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /hadoop/dfs/name
      volumes:
        - name: data
          emptyDir: {}
---
# ------------------
# HDFS: DataNode
# ------------------
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  namespace: datalake
spec:
  selector:
    app: hdfs-datanode
  ports:
    - port: 9864
      targetPort: 9864
      name: web
    - port: 9866
      targetPort: 9866
      name: data
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  namespace: datalake
spec:
  selector:
    matchLabels:
      app: hdfs-datanode
  serviceName: "hdfs-datanode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          env:
            - name: CLUSTER_NAME
              value: testcluster
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hdfs-namenode:9000
          ports:
            - containerPort: 9864
            - containerPort: 9866
          volumeMounts:
            - name: data
              mountPath: /hadoop/dfs/data
      volumes:
        - name: data
          emptyDir: {}
