server {
    listen 80;
    server_name 89.111.173.26;

    location /spark/ {
        proxy_pass http://localhost:31234/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /clickhouse/ {
        proxy_pass http://localhost:31235/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}